let hospitalDao = require('../dao/hospitalDao')

module.exports = {
    children:{
        'query':{
            handle:(req,resp)=>{
                hospitalDao.query(null,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'查询失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'update':{
            handle:(req,resp)=>{
                let hospital = req.body
                hospitalDao.update(hospital,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'更新失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'delete':{
            handle:(req,resp)=>{
                let hospital = req.body
                hospitalDao.delete(hospital,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'删除失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'insert':{
            handle:(req,resp)=>{
                let hospital = req.body
                hospitalDao.insert(hospital,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'添加失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        }
    }
}