let userDao = require('../dao/userDao')

module.exports = {
    children:{
        'query':{
            handle:(req,resp)=>{
                userDao.query(null,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'查询失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'update':{
            handle:(req,resp)=>{
                let user = req.body
                userDao.update(user,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'更新失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'delete':{
            handle:(req,resp)=>{
                let user = req.body
                userDao.delete(user,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'删除失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        },
        'insert':{
            handle:(req,resp)=>{
                let user = req.body
                userDao.insert(user,(err,result)=>{
                    if(err){
                        resp.send({
                            success:false,
                            err:'添加失败'
                        })
                    }
                    else{
                        resp.send({
                            success:true,
                            entity:result
                        })
                    }
                })
            }
        }
    }
}